name: kong_event_gw_with_confluent

services:
  # Kong Event Gateway
  kong-event-gateway:
    image: kong/kong-event-gateway-dev:latest
    container_name: keg-konnect
    ports:
      - "19092-19192:19092-19192"
      - "29092-29192:29092-29192"
      # - "8080:8080"
      # - "8443:8443"
    env_file: 
      - "konnect.env"
    environment:
      KEG__RUNTIME__DRAIN_DURATION: 1s # makes shutdown quicker, not recommended to be set like this in production
      KEG__OBSERVABILITY__LOG_FLAGS: "info,keg=debug" # Uncomment for debug logging
    healthcheck:
      test: curl -f http://localhost:8080/health/probes/liveness
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./config/certs:/var/tls
